# Generated by Django 4.1.7 on 2023-02-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accompanions', models.IntegerField(max_length=255)),
                ('event_id', models.IntegerField(max_length=255)),
            ],
        ),
    ]
