# Generated by Django 4.1.7 on 2023-02-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no_name', max_length=255)),
                ('attendance', models.BooleanField(default=False)),
                ('accompanions', models.IntegerField(default=0)),
                ('event_id', models.IntegerField()),
            ],
        ),
    ]
